import 'package:get/get.dart';

class MyLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Forgot Password': 'Forgot Password',
          'Enter your register email address here, we will send passowrd reset link.':
              'Enter your register email address here, we will send passowrd reset link.',
          'Email': 'Email',
          'Submit': 'Submit',
          'Login': 'Login',
          'Phone': 'Phone',
          'Verify OTP': 'Verify OTP',
          'Verify': 'Verify',
          'Resend OTP?': 'Resend OTP?',
          'Signup': 'Signup',
          'Registration': 'Registration',
          'Mobile': 'Mobile',
          'Continue': 'Continue',
          'Login with Apple': 'Login with Apple',
          'Or continue with': 'Or continue with',
          'Google': 'Google',
          'By signing up, I agree to Fixz':
              'By signing up, I agree to Fixz\'s ',
          'Terms & Conditions': 'Terms & Conditions',
          'and': 'and',
          'Privacy Policy': 'Privacy Policy',
          'Welcome to Maintenance Portal': 'Welcome to Maintenance Portal',
          'Feel safe and secure on Fixz':
              'At Fixz, your safety and security are our top priority.\nWe thoroughly vet all service providers and use a secure platform to protect your information.',
          'Log in': 'Log in',
          'Sign up': 'Sign up',
          'Loading...': 'Loading...',
          'Write here...': 'Write here...',
          'Sending...': 'Sending...',
          'Please write some message': 'Please write some message',
          'Track Contractor': 'Track Contractor',
          'Null place name!': 'Null place name!',
          'Edit Profile': 'Edit Profile',
          'Name': 'Name',
          'Location': 'Location',
          'Update': 'Update',
          'Support Centre': 'Support Centre',
          'Insurance': 'Insurance',
          'Privacy policy': 'Privacy policy',
          'Community Guidelines': 'Community Guidelines',
          'Help': 'Help',
          'Notifications': 'Notifications',
          'No data found': 'No data found',
          'Payment History': 'Payment History',
          'Made Payment for': 'Made Payment for',
          'My Profile': 'My Profile',
          'Name:': 'Name:',
          'Email:': 'Email:',
          'Mobile:': 'Mobile:',
          'Location:': 'Location:',
          'Location not found': 'Location not found',
          'Update Profile': 'Update Profile',
          'Review Screen': 'Review Screen',
          'commented on': 'commented on',
          'What specific kind of task?': 'What specific kind of task?',
          'Add task': 'Add task',
          'Add task alerts': 'Add task alerts',
          'Add your task alert': 'Add your task alert',
          'Please enter task': 'Please enter task',
          'Profile': 'Profile',
          'Notification': 'Notification',
          'Logout': 'Logout',
          'More Options': 'More Options',
          "Are you sure you want to logout?":
              "Are you sure you want to logout?",
          'Get Start': 'Get Start',
          'Make Payment': 'Make Payment',
          'Please fill all data': 'Please fill all data',
          'What is your main goal on Fixz?': 'What is your main goal on Fixz?',
          'Get things done': 'Get things done',
          'Earn Money': 'Earn Money',
          'I do not want to receive prodcut update or marketing material':
              'I do not want to receive prodcut update or marketing material',
          'Create your profile': 'Create your profile',
          'First Name': 'First Name',
          'Last Name': 'Last Name',
          'Enter your home post code': 'Enter your home post code',
          'Enter Postcode': 'Enter Postcode',
          'Complete your account': 'Complete your account',
          'Write comment': 'Write comment',
          'Rating Added successfully!!': 'Rating Added successfully!!',
          'Repair Request': 'Repair Request',
          'Hows the job and Contractor,Please give the review.':
              'How\'s the job and Contractor,Please give the review.',
          'Add Review': 'Add Review',
          'Please add rating first': 'Please add rating first',
          "Tasks": "Tasks",
          'More': 'More',
          'Whats your budget?': 'What\'s your budget?',
          'Price per hour': 'Price per hour',
          'Hours': 'Hours',
          'Add Task Images': 'Add Task Images',
          '(optional)': '(optional)',
          'Post Task': 'Post Task',
          'Fixed rate': 'Fixed rate',
          "Hourly rate": "Hourly rate",
          "Estimate Budget:": "Estimate Budget:",
          'Select Task Category': 'Select Task Category',
          'POSTED BY': 'POSTED BY',
          'Now': 'Now',
          'Contractor Name:': 'Contractor Name:',
          'Contact Number:': 'Contact Number:',
          'Job Quotation:': 'Job Quotation:',
          'Number of days to complete job:': 'Number of days to complete job:',
          'days': 'days',
          'LOCATION': 'LOCATION',
          'TO BE DONE ON': 'TO BE DONE ON',
          'Details': 'Details',
          'Submit Review': 'Submit Review',
          'Job Completed': 'Job Completed',
          'You will be able to track the service provider a few hours before the job':
              'You will be able to track the service provider a few hours before the job',
          'Task Details': 'Task Details',
          'OPEN': 'OPEN',
          'ASSIGNED': 'ASSIGNED',
          'COMPLETED': 'COMPLETED',
          'REVIEWED': 'REVIEWED',
          'Contractor': 'Contractor',
          'Offer has been accepted': 'Offer has been accepted',
          'Please try after sometime': 'Please try after sometime',
          'Job Assign successfully': 'Job Assign successfully',
          'Request Service Provider': 'Request Service Provider',
          'No data': 'No data',
          'Accepted': 'Accepted',
          'Completed': 'Completed',
          'No Details': 'No Details',
          'No Location': 'No Location',
          "POSTED": "POSTED",
          "offers": "offers",
          'Are you sure you want to exit?': 'Are you sure you want to exit?',
          'My tasks': 'My tasks',
          'Task': 'Task',
          'New Job Request': 'New Job Request',
          'Bookings': 'Bookings',
          'New Request': 'New Request',
          'Create Task': 'Create Task',
          "Cancel": "Cancel",
          "OK": "OK",
          'Please enter valid phone number': 'Please enter valid phone number',
          'Invalid mobile number': 'Invalid mobile number',
          'Please enter first name': 'Please enter first name',
          'Please enter last name': 'Please enter last name',
          'Please enter postal code': 'Please enter postal code',
          'Please enter valid email address':
              'Please enter valid email address',
          'Invalid email': 'Invalid email',
          'Your Location': 'Your Location',
          'Please select language': 'Please select language',
          'Change Language': 'Change Language',
          'Choose Language': 'Choose Language',
          'SAVE': 'SAVE',
          'Profile updated successfully': 'Profile updated successfully',
          'Please enter your name': 'Please enter your name',
          //
          'Task title': 'Task title',
          'Enter title': 'Enter title',
          'Describe your task': 'Describe your task',
          'write here': 'write here',
          'Add must haves': 'Add must haves',
          'Can this task completed remotely?':
              'Can this task completed remotely?',
          'Task Location(Postcode)': 'Task Location(Postcode)',
          'Enter location': 'Enter location',
          'At what time do you need the service provider?':
              'At what time do you need the service provider?',
          'Select date': 'Select date',
          'Must Have': 'Must Have',
          'Add up to 3 things the tasker needs to have or do to make an offer - e.g.':
              'Add up to 3 things the tasker needs to have or do to make an offer - e.g.',
          'Must have available on sunday morning':
              'Must have available on sunday morning',
          'Must have own van or truck': 'Must have own van or truck',
          'What much they have or do?': 'What much they have or do?',
          'Please add note': 'Please add note',
          'Add': 'Add',
          'Save': 'Save',
          'Morning': 'Morning',
          'Midday': 'Midday',
          'Afternoon': 'Afternoon',
          'Evening': 'Evening',
          'Please enter title': 'Please enter title',
          'Please enter description': 'Please enter description',
          'Please enter task location': 'Please enter task location',
          'Please select date first': 'Please select date first',
          'Please select certain time slots':
              'Please select certain time slots',
          'Please add budget': 'Please add budget',
          'Please add hour and price per hour':
              'Please add hour and price per hour',
          'Task Created Successfully!!!': 'Task Created Successfully!!!',
          'No Internet connection': 'No Internet connection',
          //
          'Task Images': 'Task Images',
          "Are you sure you want to cancel task?":
              "Are you sure you want to cancel task?",
          'Cancel Task': 'Cancel Task',
          '1 min ago': '1 min ago',
          'Send': 'Send',
          'OFFERS': 'OFFERS',
          'Message': 'Message',
          'Accept': 'Accept',
          'TASK PRICE': 'TASK PRICE',
          'Awaiting offers': 'Awaiting offers',
          'Support': 'Support',
          'Please select address type': 'Please select address type',
          '': '',
          '': '',
          '': '',
        },

        ///////////////////Arabic///////////////

        'ar_EG': {
          'Forgot Password': 'هل نسيت كلمة السر',
          'Enter your register email address here, we will send passowrd reset link.':
              'أدخل عنوان بريدك الإلكتروني للتسجيل هنا ، وسوف نرسل رابط إعادة تعيين كلمة المرور.',
          'Email': 'البريد الإلكتروني',
          'Submit': 'يُقدِّم',
          'Login': 'تسجيل الدخول',
          'Phone': 'هاتف',
          'Verify OTP': 'تحقق من OTP',
          'Verify': 'يؤكد',
          'Resend OTP?': 'إعادة إرسال OTP؟',
          'Signup': 'اشتراك',
          'Registration': 'تسجيل',
          'Mobile': 'التليفون المحمول',
          'Continue': 'يكمل',
          'Login with Apple': 'تسجيل الدخول مع Apple',
          'Or continue with': 'أو تواصل مع',
          'Google': 'جوجل',
          'By signing up, I agree to Fixz': 'بالتسجيل ، أنا أوافق على Fixz',
          'Terms & Conditions': 'البنود و الظروف',
          'and': 'و',
          'Privacy Policy': 'سياسة الخصوصية',
          'Welcome to Maintenance Portal': 'مرحبا بكم في بوابة الصيانة',
          'Feel safe and secure on Fixz':
              'في Fixz ، سلامتك وأمنك على رأس أولوياتنا.\nنحن نفحص بدقة جميع مقدمي الخدمات ونستخدم منصة آمنة لحماية معلوماتك.',
          'Log in': 'تسجيل الدخول',
          'Sign up': 'اشتراك',
          'Loading...': 'جار التحميل...',
          'Write here...': 'اكتب هنا...',
          'Sending...': 'إرسال...',
          'Please write some message': 'الرجاء كتابة بعض الرسالة',
          'Track Contractor': 'المقاول المسار',
          'Null place name!': 'اسم مكان فارغ!',
          'Edit Profile': 'تعديل الملف الشخصي',
          'Name': 'اسم',
          'Location': 'موقع',
          'Update': 'تحديث',
          'Support Centre': 'مركز الدعم',
          'Insurance': 'تأمين',
          'Privacy policy': 'سياسة الخصوصية',
          'Community Guidelines': 'إرشادات المجتمع',
          'Help': 'مساعدة',
          'Notifications': 'إشعارات',
          'No data found': 'لاتوجد بيانات',
          'Payment History': 'تاريخ الدفع',
          'Made Payment for': 'تم الدفع مقابل',
          'My Profile': 'ملفي',
          'Name:': 'اسم:',
          'Email:': 'البريد الإلكتروني:',
          'Mobile:': 'التليفون المحمول:',
          'Location:': 'موقع:',
          'Location not found': 'الموقع غير موجود',
          'Update Profile': 'تحديث الملف',
          'Review Screen': 'شاشة المراجعة',
          'commented on': 'علق على',
          'What specific kind of task?': 'ما نوع المهمة المحددة؟',
          'Add task': 'إضافة مهمة',
          'Add task alerts': 'أضف تنبيهات المهام',
          'Add your task alert': 'أضف تنبيه المهمة الخاص بك',
          'Please enter task': 'الرجاء إدخال المهمة',
          'Profile': 'الملف الشخصي',
          'Notification': 'تنبيه',
          'Logout': 'تسجيل خروج',
          'More Options': 'المزيد من الخيارات',
          "Are you sure you want to logout?":
              "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          'Get Start': 'ابدأ',
          'Make Payment': 'قم بالدفع',
          'Please fill all data': 'الرجاء تعبئة جميع البيانات',
          'What is your main goal on Fixz?': 'ما هو هدفك الرئيسي في Fixz؟',
          'Get things done': 'انجاز الامور',
          'Earn Money': 'يكتسب نقود',
          'I do not want to receive prodcut update or marketing material':
              'لا أرغب في تلقي تحديث المنتج أو مواد تسويقية',
          'Create your profile': 'اصنع حسابك الشخصي',
          'First Name': 'الاسم الاول',
          'Last Name': 'الكنية',
          'Enter your home post code': 'أدخل رمز منزلك البريدي',
          'Enter Postcode': 'أدخل الرمز البريدي',
          'Complete your account': 'أكمل حسابك',
          'Write comment': 'اكتب تعليق',
          'Rating Added successfully!!': '!!تمت إضافة التقييم بنجاح',
          'Repair Request': 'طلب إصلاح',
          'Hows the job and Contractor,Please give the review.':
              'كيف هي الوظيفة والمقاول ، يرجى إعطاء المراجعة.',
          'Add Review': 'إضافة مراجعة',
          'Please add rating first': 'الرجاء إضافة التصنيف أولا',
          "Tasks": "مهام",
          'More': 'أكثر',
          'Whats your budget?': 'ما هي ميزانيتك؟',
          'Price per hour': 'سعر الساعة',
          'Hours': 'ساعات',
          'Add Task Images': 'أضف صور المهام',
          '(optional)': '(اختياري)',
          'Post Task': 'بعد المهمة',
          'Fixed rate': 'سعر الصرف الثابت',
          "Hourly rate": "المعدل بالساعة",
          "Estimate Budget:": "تقدير الميزانية:",
          'Select Task Category': 'حدد فئة المهمة',
          'POSTED BY': 'منشور من طرف',
          'Now': 'حاليا',
          'Contractor Name:': 'اسم المقاول:',
          'Contact Number:': 'رقم الاتصال:',
          'Job Quotation:': 'عرض أسعار:',
          'Number of days to complete job:': 'عدد الأيام لإكمال الوظيفة:',
          'days': 'أيام',
          'LOCATION': 'موقعك',
          'TO BE DONE ON': 'يتعين القيام به',
          'Details': 'تفاصيل',
          'Submit Review': 'إرسال المراجعة',
          'Job Completed': 'أنجزت المهمة',
          'You will be able to track the service provider a few hours before the job':
              'ستكون قادرًا على تتبع مزود الخدمة قبل ساعات قليلة من الوظيفة',
          'Task Details': 'تفاصيل المهمة',
          'OPEN': 'افتح',
          'ASSIGNED': 'مُكَلَّف',
          'COMPLETED': 'منجز',
          'REVIEWED': 'مراجعة',
          'Contractor': 'مقاول',
          'Offer has been accepted': 'تم قبول العرض',
          'Please try after sometime': 'يرجى المحاولة بعد مرور بعض الوقت',
          'Job Assign successfully': 'تم تعيين الوظيفة بنجاح',
          'Request Service Provider': 'طلب مقدم الخدمة',
          'No data': 'لايوجد بيانات',
          'Accepted': 'وافقت',
          'Completed': 'مكتمل',
          'No Details': 'بدون تفاصيل',
          'No Location': 'لا موقع',
          "POSTED": "تم النشر",
          "offers": "عروض",
          'Are you sure you want to exit?': 'هل أنت متأكد أنك تريد الخروج؟',
          'My tasks': 'مهامي',
          'Task': 'مهمة',
          'New Job Request': 'طلب عمل جديد',
          'Bookings': 'الحجوزات',
          'New Request': 'طلب جديد',
          'Create Task': 'إنشاء مهمة',
          "Cancel": "يلغي",
          "OK": "نعم",
          'Please enter valid phone number': 'الرجاء إدخال رقم هاتف صحيح',
          'Invalid mobile number': 'رقم الجوال غير صالح',
          'Please enter first name': 'الرجاء إدخال الاسم الأول',
          'Please enter last name': 'الرجاء إدخال الاسم الأخير',
          'Please enter postal code': 'الرجاء إدخال الرمز البريدي',
          'Please enter valid email address':
              'الرجاء إدخال عنوان بريد إلكتروني صالح',
          'Invalid email': 'بريد إلكتروني خاطئ',
          'Your Location': 'موقعك',
          'Please select language': 'الرجاء تحديد اللغة',
          'Change Language': 'تغيير اللغة',
          'Choose Language': 'اختر اللغة',
          'SAVE': 'حفظ',
          'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح',
          'Please enter your name': 'من فضلك أدخل إسمك',
          'Task title': 'عنوان المهمة',
          'Enter title': 'أدخل العنوان',
          'Describe your task': 'صِف مهمتك',
          'write here': 'اكتب هنا',
          'Add must haves': 'إضافة يجب أن تمتلك',
          'Can this task completed remotely?':
              'هل يمكن أن تكتمل هذه المهمة عن بعد؟',
          'Task Location(Postcode)': 'موقع المهمة (الرمز البريدي)',
          'Enter location': 'إدخال الدولة',
          'At what time do you need the service provider?':
              'في أي وقت تحتاج مزود الخدمة؟',
          'Select date': 'حدد تاريخ',
          'Must Have': 'يجب ان يملك',
          'Add up to 3 things the tasker needs to have or do to make an offer - e.g.':
              'أضف ما يصل إلى 3 أشياء يحتاجها Tasker أو يفعلها لتقديم عرض - على سبيل المثال',
          'Must have available on sunday morning': 'يجب أن يتوفر في صباح الأحد',
          'Must have own van or truck': 'يجب أن يكون لديك فان أو شاحنة خاصة',
          'What much they have or do?': 'ماذا لديهم أو يفعلون؟',
          'Please add note': 'الرجاء إضافة ملاحظة',
          'Add': 'يضيف',
          'Save': 'يحفظ',
          'Morning': 'صباح',
          'Midday': 'منتصف النهار',
          'Afternoon': 'بعد الظهر',
          'Evening': 'اخر النهار',
          'Please enter title': 'الرجاء إدخال العنوان',
          'Please enter description': 'الرجاء إدخال الوصف',
          'Please enter task location': 'الرجاء إدخال موقع المهمة',
          'Please select date first': 'الرجاء تحديد التاريخ أولا',
          'Please select certain time slots': 'الرجاء تحديد فترات زمنية معينة',
          'Please add budget': 'الرجاء إضافة الميزانية',
          'Please add hour and price per hour':
              'الرجاء إضافة الساعة والسعر لكل ساعة',
          'Task Created Successfully!!!': 'تم إنشاء المهمة بنجاح !!!',
          'No Internet connection': 'لا يوجد اتصال بالإنترنت',
          'Task Images': 'صور المهمة',
          "Are you sure you want to cancel task?":
              "هل أنت متأكد أنك تريد إلغاء المهمة؟",
          'Cancel Task': 'إلغاء المهمة',
          '1 min ago': 'قبل دقيقة واحدة',
          'Send': 'إرسال',
          'OFFERS': 'عروض',
          'Message': 'رسالة',
          'Accept': 'قبول',
          'TASK PRICE': 'سعر المهمة',
          'Awaiting offers': 'انتظار العروض',
          'Support': 'يدعم',
          'Please select address type': 'الرجاء تحديد نوع العنوان',
          '': '',
          '': '',
          '': '',
          '': '',
        },
      };
}
