// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
// import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: renterzapp
  static const package = "renterzapp";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/app_bg.jpg
  // ignore: non_constant_identifier_names
  final app_bg_jpg =
      const AssetResource("assets/images/app_bg.jpg", packageName: null);

  /// asset: assets/images/backyard.png
  // ignore: non_constant_identifier_names
  final backyard =
      const AssetResource("assets/images/backyard.png", packageName: null);

  /// asset: assets/images/bathroom.png
  // ignore: non_constant_identifier_names
  final bathroom =
      const AssetResource("assets/images/bathroom.png", packageName: null);

  /// asset: assets/images/bed.png
  // ignore: non_constant_identifier_names
  final bed = const AssetResource("assets/images/bed.png", packageName: null);

  /// asset: assets/images/bed_beg.png
  // ignore: non_constant_identifier_names
  final bed_beg =
      const AssetResource("assets/images/bed_beg.png", packageName: null);

  /// asset: assets/images/clock.png
  // ignore: non_constant_identifier_names
  final clock =
      const AssetResource("assets/images/clock.png", packageName: null);

  /// asset: assets/images/exterior.png
  // ignore: non_constant_identifier_names
  final exterior =
      const AssetResource("assets/images/exterior.png", packageName: null);

  /// asset: assets/images/ic_calendar_orange.png
  // ignore: non_constant_identifier_names
  final ic_calendar_orange = const AssetResource(
      "assets/images/ic_calendar_orange.png",
      packageName: null);

  /// asset: assets/images/ic_circle_user.png
  // ignore: non_constant_identifier_names
  final ic_circle_user = const AssetResource("assets/images/ic_circle_user.png",
      packageName: null);

  /// asset: assets/images/ic_clock_orange.png
  // ignore: non_constant_identifier_names
  final ic_clock_orange = const AssetResource(
      "assets/images/ic_clock_orange.png",
      packageName: null);

  /// asset: assets/images/ic_edit.png
  // ignore: non_constant_identifier_names
  final ic_edit =
      const AssetResource("assets/images/ic_edit.png", packageName: null);

  /// asset: assets/images/ic_fav.png
  // ignore: non_constant_identifier_names
  final ic_fav =
      const AssetResource("assets/images/ic_fav.png", packageName: null);

  /// asset: assets/images/ic_fav_fill.png
  // ignore: non_constant_identifier_names
  final ic_fav_fill =
      const AssetResource("assets/images/ic_fav_fill.png", packageName: null);

  /// asset: assets/images/ic_launcher.png
  // ignore: non_constant_identifier_names
  final ic_launcher =
      const AssetResource("assets/images/ic_launcher.png", packageName: null);

  /// asset: assets/images/ic_location_orange.png
  // ignore: non_constant_identifier_names
  final ic_location_orange = const AssetResource(
      "assets/images/ic_location_orange.png",
      packageName: null);

  /// asset: assets/images/ic_mail.png
  // ignore: non_constant_identifier_names
  final ic_mail =
      const AssetResource("assets/images/ic_mail.png", packageName: null);

  /// asset: assets/images/ic_office.jpg
  // ignore: non_constant_identifier_names
  final ic_office_jpg =
      const AssetResource("assets/images/ic_office.jpg", packageName: null);

  /// asset: assets/images/ic_selected_button.png
  // ignore: non_constant_identifier_names
  final ic_selected_button = const AssetResource(
      "assets/images/ic_selected_button.png",
      packageName: null);

  /// asset: assets/images/ic_settings.png
  // ignore: non_constant_identifier_names
  final ic_settings =
      const AssetResource("assets/images/ic_settings.png", packageName: null);

  /// asset: assets/images/ic_unselected_button.png
  // ignore: non_constant_identifier_names
  final ic_unselected_button = const AssetResource(
      "assets/images/ic_unselected_button.png",
      packageName: null);

  /// asset: assets/images/icon_buyers.png
  // ignore: non_constant_identifier_names
  final icon_buyers =
      const AssetResource("assets/images/icon_buyers.png", packageName: null);

  /// asset: assets/images/icon_landlord.png
  // ignore: non_constant_identifier_names
  final icon_landlord =
      const AssetResource("assets/images/icon_landlord.png", packageName: null);

  /// asset: assets/images/icon_tenant.png
  // ignore: non_constant_identifier_names
  final icon_tenant =
      const AssetResource("assets/images/icon_tenant.png", packageName: null);

  /// asset: assets/images/kitchen.png
  // ignore: non_constant_identifier_names
  final kitchen =
      const AssetResource("assets/images/kitchen.png", packageName: null);

  /// asset: assets/images/laundry_room.png
  // ignore: non_constant_identifier_names
  final laundry_room =
      const AssetResource("assets/images/laundry_room.png", packageName: null);

  /// asset: assets/images/living_room.png
  // ignore: non_constant_identifier_names
  final living_room =
      const AssetResource("assets/images/living_room.png", packageName: null);

  /// asset: assets/images/logo.png
  // ignore: non_constant_identifier_names
  final logo = const AssetResource("assets/images/logo.png", packageName: null);

  /// asset: assets/images/others.png
  // ignore: non_constant_identifier_names
  final others =
      const AssetResource("assets/images/others.png", packageName: null);

  /// asset: assets/images/r1.png
  // ignore: non_constant_identifier_names
  final r1 = const AssetResource("assets/images/r1.png", packageName: null);

  /// asset: assets/images/r2.png
  // ignore: non_constant_identifier_names
  final r2 = const AssetResource("assets/images/r2.png", packageName: null);

  /// asset: assets/images/r3.png
  // ignore: non_constant_identifier_names
  final r3 = const AssetResource("assets/images/r3.png", packageName: null);

  /// asset: assets/images/r4.png
  // ignore: non_constant_identifier_names
  final r4 = const AssetResource("assets/images/r4.png", packageName: null);

  /// asset: assets/images/r5.png
  // ignore: non_constant_identifier_names
  final r5 = const AssetResource("assets/images/r5.png", packageName: null);

  /// asset: assets/images/r6.png
  // ignore: non_constant_identifier_names
  final r6 = const AssetResource("assets/images/r6.png", packageName: null);

  /// asset: assets/images/renter_logo_img.png
  // ignore: non_constant_identifier_names
  final renter_logo_img = const AssetResource(
      "assets/images/renter_logo_img.png",
      packageName: null);

  /// asset: assets/images/renterz_log.png
  // ignore: non_constant_identifier_names
  final renterz_log =
      const AssetResource("assets/images/renterz_log.png", packageName: null);

  /// asset: assets/images/repair1.png
  // ignore: non_constant_identifier_names
  final repair1 =
      const AssetResource("assets/images/repair1.png", packageName: null);

  /// asset: assets/images/repair2.png
  // ignore: non_constant_identifier_names
  final repair2 =
      const AssetResource("assets/images/repair2.png", packageName: null);

  /// asset: assets/images/repair3.png
  // ignore: non_constant_identifier_names
  final repair3 =
      const AssetResource("assets/images/repair3.png", packageName: null);

  /// asset: assets/images/repair4.png
  // ignore: non_constant_identifier_names
  final repair4 =
      const AssetResource("assets/images/repair4.png", packageName: null);

  /// asset: assets/images/repair5.png
  // ignore: non_constant_identifier_names
  final repair5 =
      const AssetResource("assets/images/repair5.png", packageName: null);

  /// asset: assets/images/repair6.png
  // ignore: non_constant_identifier_names
  final repair6 =
      const AssetResource("assets/images/repair6.png", packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();

  /// asset: assets/colors.json
  // ignore: non_constant_identifier_names
  final colors_json =
      const AssetResource("assets/colors.json", packageName: null);
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/app_bg.jpg
  // ignore: non_constant_identifier_names
  AssetImage app_bg_jpg() {
    return AssetImage(asset.app_bg_jpg.keyName);
  }

  /// asset: assets/images/backyard.png
  // ignore: non_constant_identifier_names
  AssetImage backyard() {
    return AssetImage(asset.backyard.keyName);
  }

  /// asset: assets/images/bathroom.png
  // ignore: non_constant_identifier_names
  AssetImage bathroom() {
    return AssetImage(asset.bathroom.keyName);
  }

  /// asset: assets/images/bed.png
  // ignore: non_constant_identifier_names
  AssetImage bed() {
    return AssetImage(asset.bed.keyName);
  }

  /// asset: assets/images/bed_beg.png
  // ignore: non_constant_identifier_names
  AssetImage bed_beg() {
    return AssetImage(asset.bed_beg.keyName);
  }

  /// asset: assets/images/clock.png
  // ignore: non_constant_identifier_names
  AssetImage clock() {
    return AssetImage(asset.clock.keyName);
  }

  /// asset: assets/images/exterior.png
  // ignore: non_constant_identifier_names
  AssetImage exterior() {
    return AssetImage(asset.exterior.keyName);
  }

  /// asset: assets/images/ic_calendar_orange.png
  // ignore: non_constant_identifier_names
  AssetImage ic_calendar_orange() {
    return AssetImage(asset.ic_calendar_orange.keyName);
  }

  /// asset: assets/images/ic_circle_user.png
  // ignore: non_constant_identifier_names
  AssetImage ic_circle_user() {
    return AssetImage(asset.ic_circle_user.keyName);
  }

  /// asset: assets/images/ic_clock_orange.png
  // ignore: non_constant_identifier_names
  AssetImage ic_clock_orange() {
    return AssetImage(asset.ic_clock_orange.keyName);
  }

  /// asset: assets/images/ic_edit.png
  // ignore: non_constant_identifier_names
  AssetImage ic_edit() {
    return AssetImage(asset.ic_edit.keyName);
  }

  /// asset: assets/images/ic_fav.png
  // ignore: non_constant_identifier_names
  AssetImage ic_fav() {
    return AssetImage(asset.ic_fav.keyName);
  }

  /// asset: assets/images/ic_fav_fill.png
  // ignore: non_constant_identifier_names
  AssetImage ic_fav_fill() {
    return AssetImage(asset.ic_fav_fill.keyName);
  }

  /// asset: assets/images/ic_launcher.png
  // ignore: non_constant_identifier_names
  AssetImage ic_launcher() {
    return AssetImage(asset.ic_launcher.keyName);
  }

  /// asset: assets/images/ic_location_orange.png
  // ignore: non_constant_identifier_names
  AssetImage ic_location_orange() {
    return AssetImage(asset.ic_location_orange.keyName);
  }

  /// asset: assets/images/ic_mail.png
  // ignore: non_constant_identifier_names
  AssetImage ic_mail() {
    return AssetImage(asset.ic_mail.keyName);
  }

  /// asset: assets/images/ic_office.jpg
  // ignore: non_constant_identifier_names
  AssetImage ic_office_jpg() {
    return AssetImage(asset.ic_office_jpg.keyName);
  }

  /// asset: assets/images/ic_selected_button.png
  // ignore: non_constant_identifier_names
  AssetImage ic_selected_button() {
    return AssetImage(asset.ic_selected_button.keyName);
  }

  /// asset: assets/images/ic_settings.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings() {
    return AssetImage(asset.ic_settings.keyName);
  }

  /// asset: assets/images/ic_unselected_button.png
  // ignore: non_constant_identifier_names
  AssetImage ic_unselected_button() {
    return AssetImage(asset.ic_unselected_button.keyName);
  }

  /// asset: assets/images/icon_buyers.png
  // ignore: non_constant_identifier_names
  AssetImage icon_buyers() {
    return AssetImage(asset.icon_buyers.keyName);
  }

  /// asset: assets/images/icon_landlord.png
  // ignore: non_constant_identifier_names
  AssetImage icon_landlord() {
    return AssetImage(asset.icon_landlord.keyName);
  }

  /// asset: assets/images/icon_tenant.png
  // ignore: non_constant_identifier_names
  AssetImage icon_tenant() {
    return AssetImage(asset.icon_tenant.keyName);
  }

  AssetImage icon_HomeViewer() {
    return AssetImage('assets/images/homeviewerIcon.png');
  }

  /// asset: assets/images/kitchen.png
  // ignore: non_constant_identifier_names
  AssetImage kitchen() {
    return AssetImage(asset.kitchen.keyName);
  }

  /// asset: assets/images/laundry_room.png
  // ignore: non_constant_identifier_names
  AssetImage laundry_room() {
    return AssetImage(asset.laundry_room.keyName);
  }

  /// asset: assets/images/living_room.png
  // ignore: non_constant_identifier_names
  AssetImage living_room() {
    return AssetImage(asset.living_room.keyName);
  }

  /// asset: assets/images/logo.png
  // ignore: non_constant_identifier_names
  AssetImage logo() {
    return AssetImage(asset.logo.keyName);
  }

  /// asset: assets/images/others.png
  // ignore: non_constant_identifier_names
  AssetImage others() {
    return AssetImage(asset.others.keyName);
  }

  /// asset: assets/images/r1.png
  // ignore: non_constant_identifier_names
  AssetImage r1() {
    return AssetImage(asset.r1.keyName);
  }

  /// asset: assets/images/r2.png
  // ignore: non_constant_identifier_names
  AssetImage r2() {
    return AssetImage(asset.r2.keyName);
  }

  /// asset: assets/images/r3.png
  // ignore: non_constant_identifier_names
  AssetImage r3() {
    return AssetImage(asset.r3.keyName);
  }

  /// asset: assets/images/r4.png
  // ignore: non_constant_identifier_names
  AssetImage r4() {
    return AssetImage(asset.r4.keyName);
  }

  /// asset: assets/images/r5.png
  // ignore: non_constant_identifier_names
  AssetImage r5() {
    return AssetImage(asset.r5.keyName);
  }

  /// asset: assets/images/r6.png
  // ignore: non_constant_identifier_names
  AssetImage r6() {
    return AssetImage(asset.r6.keyName);
  }

  /// asset: assets/images/renter_logo_img.png
  // ignore: non_constant_identifier_names
  AssetImage renter_logo_img() {
    return AssetImage(asset.renter_logo_img.keyName);
  }

  /// asset: assets/images/renterz_log.png
  // ignore: non_constant_identifier_names
  AssetImage renterz_log() {
    return AssetImage(asset.renterz_log.keyName);
  }

  /// asset: assets/images/repair1.png
  // ignore: non_constant_identifier_names
  AssetImage repair1() {
    return AssetImage(asset.repair1.keyName);
  }

  /// asset: assets/images/repair2.png
  // ignore: non_constant_identifier_names
  AssetImage repair2() {
    return AssetImage(asset.repair2.keyName);
  }

  /// asset: assets/images/repair3.png
  // ignore: non_constant_identifier_names
  AssetImage repair3() {
    return AssetImage(asset.repair3.keyName);
  }

  /// asset: assets/images/repair4.png
  // ignore: non_constant_identifier_names
  AssetImage repair4() {
    return AssetImage(asset.repair4.keyName);
  }

  /// asset: assets/images/repair5.png
  // ignore: non_constant_identifier_names
  AssetImage repair5() {
    return AssetImage(asset.repair5.keyName);
  }

  /// asset: assets/images/repair6.png
  // ignore: non_constant_identifier_names
  AssetImage repair6() {
    return AssetImage(asset.repair6.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();

  /// asset: assets/colors.json
  // ignore: non_constant_identifier_names
  Future<String> colors_json() {
    final str = rootBundle.loadString(asset.colors_json.keyName);
    return str;
  }
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
